name: Terraform CI
on:
  push:
    branches:
      - main
      
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Formatting for error
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init